comment:
  layout: "flags, files"
  behavior: default
  require_changes: false  
  require_base: no
  require_head: no
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
  msal-angular:
    paths: lib/msal-angular
  msal-browser:
    paths: lib/msal-browser
  msal-common:
    paths: lib/msal-common
  msal-core:
    paths: lib/msal-core
  msal-node:
    paths: lib/msal-node
  msal-react:
    paths: lib/msal-react
