name: Documentation
description: Issues with documentation for one of our libraries.
labels: [documentation, question]
body:

- type: markdown
  attributes:
    value: |
      ## Before Submitting your Issue
      If there's a problem with the documentation or samples in this repo, please consider opening a PR with the necessary changes instead.
      
      You'll find our contributing doc [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md)
      
- type: markdown
  attributes:
    value: |
      ## Issue Details

- type: dropdown
  attributes:
    label: Core Library
    multiple: true
    options: 
      - "@azure/msal or msal"
      - "@azure/msal-browser"
      - "@azure/msal-node"
      - "passport-azure-ad"
      - "adal-node"
      - "adal.js"

- type: dropdown
  attributes:
    label: Wrapper Library
    multiple: true
    options:
      - "@azure/msal-angular"
      - "@azure/msal-react"
      - "adal-angular"
      - "Not Applicable"
  validations:
    required: true

- type: input
  attributes:
    label: Documentation Location
    description: Please provide a link to the documentation this issue is about
    placeholder: "docs.microsoft.com"
  validations: 
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Please briefly describe your issue."
  validations: 
    required: true
