# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run CI

on:
  push:
    branches:
      - 'dev'
      - 'master'
  pull_request:
    paths:
      - 'lib/**/*'
      - '!**.md'
      - '.github/workflows/build-steps.yml'

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:

  build-test:
    runs-on: ubuntu-latest
    env: 
      NOT_FROM_FORK: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))

    strategy:
        fail-fast: false
        matrix:
          library:
            - msal-core
            - msal-common
            - msal-browser
            - msal-node
            - msal-angular
            - msal-react
  
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      working-directory: lib/${{ matrix.library }}
      run: npm run build:all

    - name: Lint
      working-directory: lib/${{ matrix.library }}
      run: npm run lint

    - name: Unit Tests with coverage
      working-directory: lib/${{ matrix.library }}
      run: npm run test:coverage

    - name: Coveralls
      if: success() && ${{ env.NOT_FROM_FORK == 'true' }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: ${{ matrix.library }}
        base-path: lib/${{ matrix.library }}
        path-to-lcov: lib/${{ matrix.library }}/coverage/lcov.info
        parallel: true

  Coveralls:
    needs: build-test
    runs-on: ubuntu-latest
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
