# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run CI

on:
  push:
    branches:
      - 'dev'
      - 'master'
  pull_request:
    paths:
      - 'lib/**/*'
      - '!**.md'
      - '.github/workflows/build-steps.yml'

jobs:

  build-test:
    runs-on: ubuntu-latest
    env: 
      NOT_FROM_FORK: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))

    strategy:
        fail-fast: false
        matrix:
          library:
            - msal-core
            - msal-common
            - msal-browser
            - msal-node
            - msal-angular
            - msal-react
  
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      working-directory: lib/${{ matrix.library }}
      run: npm run build:all

    - name: Lint
      working-directory: lib/${{ matrix.library }}
      run: npm run lint

    - name: Unit Tests with coverage
      working-directory: lib/${{ matrix.library }}
      run: npm run test:coverage

    - name: Upload Test Coverage to CodeCov
      if: success()
      uses: codecov/codecov-action@v1
      with:
        working-directory: lib/${{ matrix.library }}
        files: coverage/lcov.info
        flags: ${{ matrix.library }}
      

