# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: msal-node E2E Tests

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    paths: 
      - 'lib/msal-node/**/*' 
      - 'lib/msal-common/**/*'
      - 'samples/msal-node-samples/**/*'
      - 'samples/e2eTestUtils/**/*'
      - '!**.md'
      - '.github/workflows/msal-node-e2e.yml'

concurrency:
  group: node-e2e-${{github.ref}}
  cancel-in-progress: true

jobs:
  run-e2e:
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 10, 12, 14, 16 ]

    name: Node ${{ matrix.node }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node }}

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci
    
    - name: Build Package
      working-directory: samples/msal-node-samples
      run: npm run build:package
      
    - name: Install Test Tools
      working-directory: samples/msal-node-samples
      run: npm install
    
    - name: Install Auth Code Sample
      working-directory: samples/msal-node-samples/auth-code
      run: |
        npm run install:local
        npm install

    - name: Install Device Code Sample
      working-directory: samples/msal-node-samples/device-code
      run: |
        npm run install:local
        npm install

    - name: Install Silent Flow Sample
      working-directory: samples/msal-node-samples/silent-flow
      run: |
        npm run install:local
        npm install
        
    - name: E2E Tests
      working-directory: samples/msal-node-samples
      timeout-minutes: 5
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: npm test

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: samples/**/screenshots
