# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: msal-browser E2E Tests

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    paths: 
      - 'lib/msal-browser/**/*' 
      - 'lib/msal-common/**/*'
      - 'samples/msal-browser-samples/VanillaJSTestApp2.0/**/*'
      - 'samples/e2eTestUtils/**/*'
      - '!**.md'

concurrency:
  group: browser-e2e-${{github.ref}}
  cancel-in-progress: true

jobs:
  run-e2e:
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Install Test Tools
      working-directory: samples
      run: npm install

    - name: Build packages
      working-directory: samples/msal-browser-samples/VanillaJSTestApp2.0
      run: |
        npm install
        npm run build:package

    - name: E2E Tests
      working-directory: samples/msal-browser-samples/VanillaJSTestApp2.0
      timeout-minutes: 5
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: npm run test:e2e

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: samples/**/screenshots
